-- Incremental conversation metadata only. This migration intentionally does
-- not backfill historical tweets; the bounded reconciliation rollout is a
-- separate, observable operation.

ALTER TABLE public.conversations
  ADD COLUMN IF NOT EXISTS producer_source text NOT NULL DEFAULT 'legacy',
  ADD COLUMN IF NOT EXISTS resolution_status text NOT NULL DEFAULT 'legacy',
  ADD COLUMN IF NOT EXISTS first_observed_at timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS resolved_at timestamptz,
  ADD COLUMN IF NOT EXISTS attempt_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS next_attempt_at timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS last_error text;

ALTER TABLE public.conversations
  ADD CONSTRAINT conversations_resolution_status_check
  CHECK (
    resolution_status IN (
      'legacy',
      'authoritative',
      'root',
      'pending',
      'inherited'
    )
  ) NOT VALID;

ALTER TABLE public.conversations
  ADD CONSTRAINT conversations_attempt_count_check
  CHECK (attempt_count >= 0) NOT VALID;

CREATE INDEX IF NOT EXISTS conversations_pending_resolution_idx
  ON public.conversations (next_attempt_at, tweet_id)
  WHERE resolution_status = 'pending';

CREATE TABLE public.conversation_resolution_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz NOT NULL DEFAULT now(),
  attempted integer NOT NULL CHECK (attempted >= 0),
  resolved integer NOT NULL CHECK (resolved >= 0),
  deferred integer NOT NULL CHECK (deferred >= 0),
  ready_after integer NOT NULL CHECK (ready_after >= 0)
);

CREATE INDEX conversation_resolution_runs_finished_at_idx
  ON public.conversation_resolution_runs (finished_at DESC);

CREATE TABLE public.conversation_resolution_reconciliation (
  id boolean PRIMARY KEY DEFAULT true CHECK (id),
  status text NOT NULL DEFAULT 'paused'
    CHECK (status IN ('paused', 'running', 'complete')),
  cursor_tweet_id text,
  high_watermark_tweet_id text,
  examined_count bigint NOT NULL DEFAULT 0 CHECK (examined_count >= 0),
  queued_count bigint NOT NULL DEFAULT 0 CHECK (queued_count >= 0),
  root_count bigint NOT NULL DEFAULT 0 CHECK (root_count >= 0),
  started_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  last_error text
);

INSERT INTO public.conversation_resolution_reconciliation (id)
VALUES (true);

CREATE VIEW public.conversation_resolution_health
WITH (security_invoker = true)
AS
SELECT
  producer_source,
  resolution_status,
  count(*)::bigint AS row_count,
  max(first_observed_at) AS latest_observed_at,
  max(resolved_at) AS latest_resolved_at,
  min(next_attempt_at) FILTER (
    WHERE resolution_status = 'pending'
  ) AS oldest_ready_at,
  max(attempt_count) AS max_attempt_count
FROM public.conversations
GROUP BY producer_source, resolution_status;

ALTER TABLE public.conversation_resolution_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_resolution_reconciliation ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.conversation_resolution_runs FROM anon, authenticated;
REVOKE ALL ON public.conversation_resolution_reconciliation FROM anon, authenticated;
GRANT SELECT, INSERT, DELETE ON public.conversation_resolution_runs TO service_role;
GRANT SELECT, INSERT, UPDATE ON public.conversation_resolution_reconciliation
  TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.conversation_resolution_runs_id_seq
  TO service_role;
REVOKE ALL ON public.conversation_resolution_health FROM anon, authenticated;
GRANT SELECT ON public.conversation_resolution_health TO service_role, readclient;

CREATE OR REPLACE FUNCTION private.queue_incremental_conversation()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_is_root boolean := NEW.reply_to_tweet_id IS NULL;
  v_source text := CASE
    WHEN NEW.archive_upload_id IS NOT NULL THEN 'archive_upload'
    ELSE 'database_trigger'
  END;
BEGIN
  INSERT INTO public.conversations (
    tweet_id,
    conversation_id,
    producer_source,
    resolution_status,
    resolved_at,
    attempt_count,
    next_attempt_at,
    last_error
  )
  VALUES (
    NEW.tweet_id,
    CASE WHEN v_is_root THEN NEW.tweet_id ELSE NULL END,
    v_source,
    CASE WHEN v_is_root THEN 'root' ELSE 'pending' END,
    CASE WHEN v_is_root THEN now() ELSE NULL END,
    0,
    now(),
    NULL
  )
  ON CONFLICT (tweet_id) DO UPDATE
  SET
    conversation_id = CASE
      WHEN public.conversations.resolution_status = 'authoritative'
        THEN public.conversations.conversation_id
      WHEN v_is_root THEN EXCLUDED.conversation_id
      ELSE NULL
    END,
    producer_source = CASE
      WHEN public.conversations.resolution_status = 'authoritative'
        THEN public.conversations.producer_source
      ELSE EXCLUDED.producer_source
    END,
    resolution_status = CASE
      WHEN public.conversations.resolution_status = 'authoritative'
        THEN 'authoritative'
      ELSE EXCLUDED.resolution_status
    END,
    resolved_at = CASE
      WHEN public.conversations.resolution_status = 'authoritative'
        THEN public.conversations.resolved_at
      ELSE EXCLUDED.resolved_at
    END,
    attempt_count = CASE
      WHEN public.conversations.resolution_status = 'authoritative'
        THEN public.conversations.attempt_count
      ELSE 0
    END,
    next_attempt_at = CASE
      WHEN public.conversations.resolution_status = 'authoritative'
        THEN public.conversations.next_attempt_at
      ELSE now()
    END,
    last_error = NULL;

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.queue_incremental_conversation() FROM PUBLIC;

DROP TRIGGER IF EXISTS queue_incremental_conversation ON public.tweets;
CREATE TRIGGER queue_incremental_conversation
  AFTER INSERT OR UPDATE OF reply_to_tweet_id ON public.tweets
  FOR EACH ROW EXECUTE FUNCTION private.queue_incremental_conversation();

CREATE OR REPLACE FUNCTION private.process_conversation_resolution_batch(
  p_limit integer DEFAULT 500,
  p_now timestamptz DEFAULT now()
)
RETURNS TABLE (
  attempted integer,
  resolved integer,
  deferred integer,
  ready_after integer
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_started_at timestamptz := clock_timestamp();
  v_attempted integer := 0;
  v_resolved integer := 0;
  v_deferred integer := 0;
  v_ready_after integer := 0;
BEGIN
  IF p_limit < 1 OR p_limit > 5000 THEN
    RAISE EXCEPTION 'conversation resolution batch must be between 1 and 5000';
  END IF;

  WITH candidates AS MATERIALIZED (
    SELECT
      c.tweet_id,
      parent.conversation_id AS parent_conversation_id
    FROM public.conversations AS c
    INNER JOIN public.tweets AS t ON t.tweet_id = c.tweet_id
    LEFT JOIN public.conversations AS parent
      ON parent.tweet_id = t.reply_to_tweet_id
    WHERE c.resolution_status = 'pending'
      AND c.next_attempt_at <= p_now
      AND t.reply_to_tweet_id IS NOT NULL
    ORDER BY c.next_attempt_at, c.tweet_id
    LIMIT p_limit
    FOR UPDATE OF c SKIP LOCKED
  ),
  updated_rows AS (
    UPDATE public.conversations AS child
    SET
      conversation_id = candidate.parent_conversation_id,
      resolution_status = CASE
        WHEN candidate.parent_conversation_id IS NOT NULL THEN 'inherited'
        ELSE 'pending'
      END,
      resolved_at = CASE
        WHEN candidate.parent_conversation_id IS NOT NULL THEN p_now
        ELSE NULL
      END,
      attempt_count = child.attempt_count + 1,
      next_attempt_at = CASE
        WHEN candidate.parent_conversation_id IS NOT NULL THEN p_now
        ELSE p_now + make_interval(
          secs => least(3600, power(2, least(child.attempt_count, 11)))
        )
      END,
      last_error = CASE
        WHEN candidate.parent_conversation_id IS NOT NULL THEN NULL
        ELSE 'parent conversation is not available yet'
      END
    FROM candidates AS candidate
    WHERE child.tweet_id = candidate.tweet_id
    RETURNING child.resolution_status
  )
  SELECT
    (SELECT count(*)::integer FROM candidates),
    count(*) FILTER (
      WHERE resolution_status = 'inherited'
    )::integer,
    count(*) FILTER (
      WHERE resolution_status = 'pending'
    )::integer
  FROM updated_rows
  INTO v_attempted, v_resolved, v_deferred;

  SELECT count(*)::integer
  INTO v_ready_after
  FROM public.conversations
  WHERE resolution_status = 'pending'
    AND next_attempt_at <= p_now;

  INSERT INTO public.conversation_resolution_runs (
    started_at,
    finished_at,
    attempted,
    resolved,
    deferred,
    ready_after
  ) VALUES (
    v_started_at,
    clock_timestamp(),
    v_attempted,
    v_resolved,
    v_deferred,
    v_ready_after
  );

  DELETE FROM public.conversation_resolution_runs
  WHERE finished_at < p_now - interval '7 days';

  RETURN QUERY SELECT v_attempted, v_resolved, v_deferred, v_ready_after;
END;
$$;

REVOKE ALL ON FUNCTION private.process_conversation_resolution_batch(integer, timestamptz)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION private.process_conversation_resolution_batch(integer, timestamptz)
  TO service_role;

CREATE OR REPLACE FUNCTION private.configure_conversation_resolution_reconciliation(
  p_run boolean DEFAULT false,
  p_reset boolean DEFAULT false
)
RETURNS TABLE (
  status text,
  cursor_tweet_id text,
  high_watermark_tweet_id text,
  examined_count bigint,
  queued_count bigint,
  root_count bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_high_watermark text;
BEGIN
  SELECT max(tweets.tweet_id)
  INTO v_high_watermark
  FROM public.tweets;

  RETURN QUERY
  UPDATE public.conversation_resolution_reconciliation AS state
  SET
    status = CASE WHEN p_run THEN 'running' ELSE 'paused' END,
    cursor_tweet_id = CASE WHEN p_reset THEN NULL ELSE state.cursor_tweet_id END,
    high_watermark_tweet_id = CASE
      WHEN p_reset OR state.high_watermark_tweet_id IS NULL
        THEN v_high_watermark
      ELSE state.high_watermark_tweet_id
    END,
    examined_count = CASE WHEN p_reset THEN 0 ELSE state.examined_count END,
    queued_count = CASE WHEN p_reset THEN 0 ELSE state.queued_count END,
    root_count = CASE WHEN p_reset THEN 0 ELSE state.root_count END,
    started_at = CASE
      WHEN p_reset OR state.started_at IS NULL THEN now()
      ELSE state.started_at
    END,
    updated_at = now(),
    last_error = NULL
  WHERE state.id
  RETURNING
    state.status,
    state.cursor_tweet_id,
    state.high_watermark_tweet_id,
    state.examined_count,
    state.queued_count,
    state.root_count;
END;
$$;

CREATE OR REPLACE FUNCTION private.process_conversation_resolution_reconciliation_batch(
  p_limit integer DEFAULT 500,
  p_dry_run boolean DEFAULT false
)
RETURNS TABLE (
  examined integer,
  queued integer,
  roots integer,
  next_cursor text,
  complete boolean
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_state public.conversation_resolution_reconciliation%ROWTYPE;
  v_examined integer := 0;
  v_queued integer := 0;
  v_roots integer := 0;
  v_next_cursor text;
  v_complete boolean := false;
BEGIN
  IF p_limit < 1 OR p_limit > 5000 THEN
    RAISE EXCEPTION 'conversation reconciliation batch must be between 1 and 5000';
  END IF;

  SELECT *
  INTO v_state
  FROM public.conversation_resolution_reconciliation
  WHERE id
  FOR UPDATE;

  IF v_state.high_watermark_tweet_id IS NULL THEN
    RAISE EXCEPTION 'configure conversation reconciliation before processing';
  END IF;

  IF NOT p_dry_run AND v_state.status <> 'running' THEN
    RAISE EXCEPTION 'conversation reconciliation is %', v_state.status;
  END IF;

  IF p_dry_run THEN
    WITH candidates AS MATERIALIZED (
      SELECT tweets.tweet_id, tweets.reply_to_tweet_id
      FROM public.tweets AS tweets
      WHERE (
        v_state.cursor_tweet_id IS NULL
        OR tweets.tweet_id > v_state.cursor_tweet_id
      )
        AND tweets.tweet_id <= v_state.high_watermark_tweet_id
      ORDER BY tweets.tweet_id
      LIMIT p_limit
    )
    SELECT
      count(*)::integer,
      count(*) FILTER (
        WHERE existing.tweet_id IS NULL
          OR (
            existing.conversation_id IS NULL
            AND existing.resolution_status <> 'authoritative'
          )
      )::integer,
      count(*) FILTER (
        WHERE candidate.reply_to_tweet_id IS NULL
          AND (
            existing.tweet_id IS NULL
            OR (
              existing.conversation_id IS NULL
              AND existing.resolution_status <> 'authoritative'
            )
          )
      )::integer,
      max(candidate.tweet_id)
    INTO v_examined, v_queued, v_roots, v_next_cursor
    FROM candidates AS candidate
    LEFT JOIN public.conversations AS existing
      ON existing.tweet_id = candidate.tweet_id;
  ELSE
    WITH candidates AS MATERIALIZED (
      SELECT tweets.tweet_id, tweets.reply_to_tweet_id
      FROM public.tweets AS tweets
      WHERE (
        v_state.cursor_tweet_id IS NULL
        OR tweets.tweet_id > v_state.cursor_tweet_id
      )
        AND tweets.tweet_id <= v_state.high_watermark_tweet_id
      ORDER BY tweets.tweet_id
      LIMIT p_limit
    ), changed_rows AS (
      INSERT INTO public.conversations (
        tweet_id,
        conversation_id,
        producer_source,
        resolution_status,
        resolved_at,
        attempt_count,
        next_attempt_at,
        last_error
      )
      SELECT
        candidate.tweet_id,
        CASE
          WHEN candidate.reply_to_tweet_id IS NULL THEN candidate.tweet_id
          ELSE NULL
        END,
        'historical_reconciliation',
        CASE
          WHEN candidate.reply_to_tweet_id IS NULL THEN 'root'
          ELSE 'pending'
        END,
        CASE
          WHEN candidate.reply_to_tweet_id IS NULL THEN now()
          ELSE NULL
        END,
        0,
        now(),
        NULL
      FROM candidates AS candidate
      ON CONFLICT (tweet_id) DO UPDATE
      SET
        conversation_id = EXCLUDED.conversation_id,
        producer_source = EXCLUDED.producer_source,
        resolution_status = EXCLUDED.resolution_status,
        resolved_at = EXCLUDED.resolved_at,
        attempt_count = 0,
        next_attempt_at = now(),
        last_error = NULL
      WHERE public.conversations.conversation_id IS NULL
        AND public.conversations.resolution_status <> 'authoritative'
      RETURNING resolution_status
    )
    SELECT
      (SELECT count(*)::integer FROM candidates),
      count(*)::integer,
      count(*) FILTER (WHERE resolution_status = 'root')::integer,
      (SELECT max(tweet_id) FROM candidates)
    INTO v_examined, v_queued, v_roots, v_next_cursor
    FROM changed_rows;
  END IF;

  v_complete := v_examined < p_limit
    OR v_next_cursor >= v_state.high_watermark_tweet_id;

  IF NOT p_dry_run THEN
    UPDATE public.conversation_resolution_reconciliation AS state
    SET
      status = CASE WHEN v_complete THEN 'complete' ELSE 'running' END,
      cursor_tweet_id = COALESCE(v_next_cursor, state.cursor_tweet_id),
      examined_count = state.examined_count + v_examined,
      queued_count = state.queued_count + v_queued,
      root_count = state.root_count + v_roots,
      updated_at = now(),
      last_error = NULL
    WHERE state.id;
  END IF;

  RETURN QUERY
  SELECT v_examined, v_queued, v_roots, v_next_cursor, v_complete;
END;
$$;

REVOKE ALL ON FUNCTION private.configure_conversation_resolution_reconciliation(boolean, boolean)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION private.process_conversation_resolution_reconciliation_batch(integer, boolean)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION private.configure_conversation_resolution_reconciliation(boolean, boolean)
  TO service_role;
GRANT EXECUTE ON FUNCTION private.process_conversation_resolution_reconciliation_batch(integer, boolean)
  TO service_role;

CREATE OR REPLACE FUNCTION private.community_archive_monitoring_conversation_resolution_health()
RETURNS TABLE (
  producer_source text,
  resolution_status text,
  row_count bigint,
  latest_observed_at timestamptz,
  latest_resolved_at timestamptz,
  oldest_ready_at timestamptz,
  max_attempt_count integer
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT
    health.producer_source,
    health.resolution_status,
    health.row_count,
    health.latest_observed_at,
    health.latest_resolved_at,
    health.oldest_ready_at,
    health.max_attempt_count
  FROM public.conversation_resolution_health AS health;
$$;

CREATE OR REPLACE FUNCTION private.community_archive_monitoring_conversation_resolution_worker()
RETURNS TABLE (
  finished_at timestamptz,
  attempted integer,
  resolved integer,
  deferred integer,
  ready_after integer
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT
    latest.finished_at,
    COALESCE(latest.attempted, 0),
    COALESCE(latest.resolved, 0),
    COALESCE(latest.deferred, 0),
    COALESCE(latest.ready_after, 0)
  FROM (VALUES (true)) AS sentinel(include_row)
  LEFT JOIN LATERAL (
    SELECT
      runs.finished_at,
      runs.attempted,
      runs.resolved,
      runs.deferred,
      runs.ready_after
    FROM public.conversation_resolution_runs AS runs
    ORDER BY runs.finished_at DESC
    LIMIT 1
  ) AS latest ON sentinel.include_row;
$$;

CREATE OR REPLACE FUNCTION private.community_archive_monitoring_conversation_reconciliation()
RETURNS TABLE (
  status text,
  examined_count bigint,
  queued_count bigint,
  root_count bigint,
  started_at timestamptz,
  updated_at timestamptz
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT
    state.status,
    state.examined_count,
    state.queued_count,
    state.root_count,
    state.started_at,
    state.updated_at
  FROM public.conversation_resolution_reconciliation AS state
  WHERE state.id;
$$;

REVOKE ALL ON FUNCTION private.community_archive_monitoring_conversation_resolution_health()
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION private.community_archive_monitoring_conversation_resolution_worker()
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION private.community_archive_monitoring_conversation_reconciliation()
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION private.community_archive_monitoring_conversation_resolution_health()
  TO service_role;
GRANT EXECUTE ON FUNCTION private.community_archive_monitoring_conversation_resolution_worker()
  TO service_role;
GRANT EXECUTE ON FUNCTION private.community_archive_monitoring_conversation_reconciliation()
  TO service_role;

DO $$
DECLARE
  v_job_id bigint;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    SELECT jobid INTO v_job_id
    FROM cron.job
    WHERE jobname = 'resolve-conversations-incremental';

    IF v_job_id IS NOT NULL THEN
      PERFORM cron.unschedule(v_job_id);
    END IF;

    PERFORM cron.schedule(
      'resolve-conversations-incremental',
      '* * * * *',
      'SELECT private.process_conversation_resolution_batch(500);'
    );
  END IF;
END;
$$;

COMMENT ON TABLE public.conversation_resolution_runs IS
  'Seven-day telemetry for the bounded incremental conversation resolver.';
COMMENT ON TABLE public.conversation_resolution_reconciliation IS
  'Durable cursor and progress for an explicitly enabled bounded historical reconciliation.';
COMMENT ON VIEW public.conversation_resolution_health IS
  'Conversation coverage, freshness, retry, and backlog metrics grouped by ingestion source and resolution status.';
COMMENT ON FUNCTION private.process_conversation_resolution_batch(integer, timestamptz) IS
  'Resolves a bounded SKIP LOCKED batch of pending replies. Safe to rerun; does not perform historical discovery.';
