-- Curated Gallery entries need published project ids so the existing like API
-- can persist likes for every visible card. Existing submissions win on slug.
INSERT INTO public.community_projects (
  slug,
  name,
  project_url,
  creator_name,
  creator_handle,
  category,
  description,
  archive_use,
  source_post_url,
  tags,
  submitter_username,
  status,
  featured,
  submitted_at,
  published_at
)
VALUES
  (
    'bangers',
    'Bangers',
    '/bangers',
    'Community Archive',
    NULL,
    'Tools',
    'Browse popular archived posts, search by keyword, and explore different time periods and rankings.',
    'Ranks posts from participating accounts using archived engagement and community interactions.',
    '/bangers',
    ARRAY['Discovery', 'Popular tweets', 'Search'],
    'community-archive',
    'published',
    true,
    '2026-09-18T12:00:00Z',
    '2026-09-18T12:00:00Z'
  ),
  (
    'pairwise',
    'Pairwise',
    'https://strangestloop.io/pairwise',
    'Loopy',
    'strangestloop',
    'Tools',
    'Explore replies between two archive contributors, their shared words, and when they talk, in a searchable conversation view.',
    'Brings together archived replies between two people to show their conversations over time.',
    'https://strangestloop.io/coding/',
    ARRAY['Conversations', 'Personal archive', 'Relationships'],
    'strangestloop',
    'published',
    true,
    '2026-09-18T12:00:00Z',
    '2026-09-18T12:00:00Z'
  ),
  (
    'birdseye',
    'Birdseye',
    '/birdseye',
    'Community Archive',
    NULL,
    'Tools',
    'A topic-by-topic view of saved archive analyses, with themes, ideas, referenced posts over time, and links to the original conversations.',
    'Reuses existing Birdseye analyses of archived posts. Browse topic groups and follow the cited source tweets on Community Archive.',
    '/birdseye',
    ARRAY['Personal archive', 'Topics', 'AI analysis'],
    'community-archive',
    'published',
    true,
    '2026-09-07T12:00:00Z',
    '2026-09-07T12:00:00Z'
  ),
  (
    'strands',
    'Strands',
    '/strands',
    'Community Archive',
    NULL,
    'Experiments',
    'Read the original Best Strands collection: summaries of ideas that spread through the community, with key posts and links back to each conversation.',
    'Reuses the existing ranked strand analyses and their source references from the archive. Each strand has its own shareable page.',
    '/strands',
    ARRAY['Ideas', 'Conversations', 'AI analysis'],
    'community-archive',
    'published',
    true,
    '2026-09-07T12:00:00Z',
    '2026-09-07T12:00:00Z'
  ),
  (
    'model-behavior-reports',
    'Model Behavior Reports',
    'https://modelbehavior.report/',
    'Alexandre Variengien',
    'A_Variengien',
    'Research',
    'Browse crowdsourced reports of models’ personalities, tendencies, and surprising actions, with summaries that update as new observations appear.',
    'Collects public behavior reports from X through the Community Archive and groups them by model to separate recurring patterns from one-offs.',
    'https://x.com/A_Variengien/status/2103163809213145552',
    ARRAY['LLM behavior', 'Crowdsourced research', 'Model reports'],
    'A_Variengien',
    'published',
    true,
    '2026-09-24T12:00:00Z',
    '2026-09-24T12:00:00Z'
  )
ON CONFLICT (slug) DO NOTHING;
